name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-8-jdk libffi-dev
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug
          cp ./bin/*.apk $GITHUB_WORKSPACE

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: MyApp.apk
          path: ./*.apk
