name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y python3-pip openjdk-8-jdk libffi-dev unzip
          echo "Installing Buildozer and Cython..."
          pip install buildozer cython
          echo "Buildozer and Cython installed."

      - name: Install Android SDK Command-Line Tools
        run: |
          echo "Downloading Android SDK command-line tools..."
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip cmdline-tools.zip -d $HOME/android-sdk/
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools

      - name: Install Android SDK Packages
        env:
          ANDROID_SDK_ROOT: $HOME/android-sdk
          PATH: $PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools
        run: |
          echo "Accepting SDK licenses and installing platform tools..."
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0" "sources;android-31"

      - name: Verify Buildozer and SDK Installation
        run: |
          echo "Verifying Buildozer and SDK installations..."
          buildozer --version
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --version

      - name: Build APK
        env:
          ANDROID_SDK_ROOT: $HOME/android-sdk
          PATH: $PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools
        run: |
          echo "Building APK with Buildozer..."
          buildozer android debug
          cp ./bin/*.apk $GITHUB_WORKSPACE

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MyApp.apk
          path: ./*.apk
